INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('3_4_Sit-Up','3/4 Sit-Up','core','bodyweight','strength','beginner'),
('90_90_Hamstring','90/90 Hamstring','legs','bodyweight','stretching','beginner'),
('Ab_Crunch_Machine','Ab Crunch Machine','core','machine','strength','intermediate'),
('Ab_Roller','Ab Roller','core','other','strength','intermediate'),
('Adductor','Adductor','legs','other','stretching','intermediate'),
('Adductor_Groin','Adductor/Groin','legs','other','stretching','intermediate'),
('Advanced_Kettlebell_Windmill','Advanced Kettlebell Windmill','core','kettlebell','strength','intermediate'),
('Air_Bike','Air Bike','core','bodyweight','strength','beginner'),
('All_Fours_Quad_Stretch','All Fours Quad Stretch','legs','bodyweight','stretching','intermediate'),
('Alternate_Hammer_Curl','Alternate Hammer Curl','arms','dumbbell','strength','beginner'),
('Alternate_Heel_Touchers','Alternate Heel Touchers','core','bodyweight','strength','beginner'),
('Alternate_Incline_Dumbbell_Curl','Alternate Incline Dumbbell Curl','arms','dumbbell','strength','beginner'),
('Alternate_Leg_Diagonal_Bound','Alternate Leg Diagonal Bound','legs','other','plyometrics','beginner'),
('Alternating_Cable_Shoulder_Press','Alternating Cable Shoulder Press','shoulders','cable','strength','beginner'),
('Alternating_Deltoid_Raise','Alternating Deltoid Raise','shoulders','dumbbell','strength','beginner'),
('Alternating_Floor_Press','Alternating Floor Press','chest','kettlebell','strength','beginner'),
('Alternating_Hang_Clean','Alternating Hang Clean','legs','kettlebell','strength','intermediate'),
('Alternating_Kettlebell_Press','Alternating Kettlebell Press','shoulders','kettlebell','strength','intermediate'),
('Alternating_Kettlebell_Row','Alternating Kettlebell Row','back','kettlebell','strength','intermediate'),
('Alternating_Renegade_Row','Alternating Renegade Row','back','kettlebell','strength','expert'),
('Ankle_Circles','Ankle Circles','legs','other','stretching','beginner'),
('Ankle_On_The_Knee','Ankle On The Knee','legs','other','stretching','beginner'),
('Anterior_Tibialis-SMR','Anterior Tibialis-SMR','legs','other','stretching','intermediate'),
('Anti-Gravity_Press','Anti-Gravity Press','shoulders','barbell','strength','beginner'),
('Arm_Circles','Arm Circles','shoulders','other','stretching','beginner'),
('Arnold_Dumbbell_Press','Arnold Dumbbell Press','shoulders','dumbbell','strength','intermediate'),
('Around_The_Worlds','Around The Worlds','chest','dumbbell','strength','intermediate'),
('Atlas_Stone_Trainer','Atlas Stone Trainer','back','other','strongman','intermediate'),
('Atlas_Stones','Atlas Stones','back','other','strongman','expert'),
('Axle_Deadlift','Axle Deadlift','back','other','strongman','intermediate'),
('Back_Flyes_-_With_Bands','Back Flyes - With Bands','shoulders','bands','strength','beginner'),
('Backward_Drag','Backward Drag','legs','other','strongman','beginner'),
('Backward_Medicine_Ball_Throw','Backward Medicine Ball Throw','shoulders','other','plyometrics','beginner'),
('Balance_Board','Balance Board','legs','other','strength','beginner'),
('Ball_Leg_Curl','Ball Leg Curl','legs','other','strength','beginner'),
('Band_Assisted_Pull-Up','Band Assisted Pull-Up','back','other','strength','beginner'),
('Band_Good_Morning','Band Good Morning','legs','bands','powerlifting','beginner'),
('Band_Good_Morning_Pull_Through','Band Good Morning (Pull Through)','legs','bands','powerlifting','beginner'),
('Band_Hip_Adductions','Band Hip Adductions','legs','bands','strength','beginner'),
('Band_Pull_Apart','Band Pull Apart','shoulders','bands','strength','beginner'),
('Band_Skull_Crusher','Band Skull Crusher','arms','bands','strength','beginner'),
('Barbell_Ab_Rollout','Barbell Ab Rollout','core','barbell','strength','intermediate'),
('Barbell_Ab_Rollout_-_On_Knees','Barbell Ab Rollout - On Knees','core','barbell','strength','expert'),
('Barbell_Bench_Press_-_Medium_Grip','Barbell Bench Press - Medium Grip','chest','barbell','strength','beginner'),
('Barbell_Curl','Barbell Curl','arms','barbell','strength','beginner'),
('Barbell_Curls_Lying_Against_An_Incline','Barbell Curls Lying Against An Incline','arms','barbell','strength','beginner'),
('Barbell_Deadlift','Barbell Deadlift','back','barbell','strength','intermediate'),
('Barbell_Full_Squat','Barbell Full Squat','legs','barbell','strength','intermediate'),
('Barbell_Glute_Bridge','Barbell Glute Bridge','legs','barbell','powerlifting','intermediate'),
('Barbell_Guillotine_Bench_Press','Barbell Guillotine Bench Press','chest','barbell','strength','intermediate')
ON CONFLICT (external_id) DO NOTHING;