INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Barbell_Hack_Squat','Barbell Hack Squat','legs','barbell','strength','intermediate'),
('Barbell_Hip_Thrust','Barbell Hip Thrust','legs','barbell','powerlifting','intermediate'),
('Barbell_Incline_Bench_Press_-_Medium_Grip','Barbell Incline Bench Press - Medium Grip','chest','barbell','strength','beginner'),
('Barbell_Incline_Shoulder_Raise','Barbell Incline Shoulder Raise','shoulders','barbell','strength','beginner'),
('Barbell_Lunge','Barbell Lunge','legs','barbell','strength','intermediate'),
('Barbell_Rear_Delt_Row','Barbell Rear Delt Row','shoulders','barbell','strength','beginner'),
('Barbell_Rollout_from_Bench','Barbell Rollout from Bench','core','barbell','strength','intermediate'),
('Barbell_Seated_Calf_Raise','Barbell Seated Calf Raise','legs','barbell','strength','beginner'),
('Barbell_Shoulder_Press','Barbell Shoulder Press','shoulders','barbell','strength','intermediate'),
('Barbell_Shrug','Barbell Shrug','back','barbell','strength','beginner'),
('Barbell_Shrug_Behind_The_Back','Barbell Shrug Behind The Back','back','barbell','strength','beginner'),
('Barbell_Side_Bend','Barbell Side Bend','core','barbell','strength','beginner'),
('Barbell_Side_Split_Squat','Barbell Side Split Squat','legs','barbell','strength','beginner'),
('Barbell_Squat','Barbell Squat','legs','barbell','strength','beginner'),
('Barbell_Squat_To_A_Bench','Barbell Squat To A Bench','legs','barbell','strength','expert'),
('Barbell_Step_Ups','Barbell Step Ups','legs','barbell','strength','intermediate'),
('Barbell_Walking_Lunge','Barbell Walking Lunge','legs','barbell','strength','beginner'),
('Battling_Ropes','Battling Ropes','shoulders','other','strength','beginner'),
('Bear_Crawl_Sled_Drags','Bear Crawl Sled Drags','legs','other','strongman','beginner'),
('Behind_Head_Chest_Stretch','Behind Head Chest Stretch','chest','other','stretching','expert'),
('Bench_Dips','Bench Dips','arms','bodyweight','strength','beginner'),
('Bench_Jump','Bench Jump','legs','bodyweight','plyometrics','intermediate'),
('Bench_Press_-_Powerlifting','Bench Press - Powerlifting','arms','barbell','powerlifting','intermediate'),
('Bench_Press_-_With_Bands','Bench Press - With Bands','chest','bands','strength','beginner'),
('Bench_Press_with_Chains','Bench Press with Chains','arms','barbell','powerlifting','expert'),
('Bench_Sprint','Bench Sprint','legs','other','plyometrics','beginner'),
('Bent-Arm_Barbell_Pullover','Bent-Arm Barbell Pullover','back','barbell','strength','intermediate'),
('Bent-Arm_Dumbbell_Pullover','Bent-Arm Dumbbell Pullover','chest','dumbbell','strength','intermediate'),
('Bent-Knee_Hip_Raise','Bent-Knee Hip Raise','core','bodyweight','strength','beginner'),
('Bent_Over_Barbell_Row','Bent Over Barbell Row','back','barbell','strength','beginner'),
('Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench','Bent Over Dumbbell Rear Delt Raise With Head On Bench','shoulders','dumbbell','strength','beginner'),
('Bent_Over_Low-Pulley_Side_Lateral','Bent Over Low-Pulley Side Lateral','shoulders','cable','strength','beginner'),
('Bent_Over_One-Arm_Long_Bar_Row','Bent Over One-Arm Long Bar Row','back','barbell','strength','beginner'),
('Bent_Over_Two-Arm_Long_Bar_Row','Bent Over Two-Arm Long Bar Row','back','barbell','strength','intermediate'),
('Bent_Over_Two-Dumbbell_Row','Bent Over Two-Dumbbell Row','back','dumbbell','strength','beginner'),
('Bent_Over_Two-Dumbbell_Row_With_Palms_In','Bent Over Two-Dumbbell Row With Palms In','back','dumbbell','strength','beginner'),
('Bent_Press','Bent Press','core','kettlebell','strength','expert'),
('Bicycling','Bicycling','legs','other','cardio','beginner'),
('Bicycling_Stationary','Bicycling, Stationary','legs','machine','cardio','beginner'),
('Board_Press','Board Press','arms','barbell','powerlifting','intermediate'),
('Body-Up','Body-Up','arms','bodyweight','strength','intermediate'),
('Body_Tricep_Press','Body Tricep Press','arms','bodyweight','strength','beginner'),
('Bodyweight_Flyes','Bodyweight Flyes','chest','barbell','strength','intermediate'),
('Bodyweight_Mid_Row','Bodyweight Mid Row','back','other','strength','intermediate'),
('Bodyweight_Squat','Bodyweight Squat','legs','bodyweight','strength','beginner'),
('Bodyweight_Walking_Lunge','Bodyweight Walking Lunge','legs','other','strength','beginner'),
('Bosu_Ball_Cable_Crunch_With_Side_Bends','Bosu Ball Cable Crunch With Side Bends','core','cable','strength','beginner'),
('Bottoms-Up_Clean_From_The_Hang_Position','Bottoms-Up Clean From The Hang Position','arms','kettlebell','strength','intermediate'),
('Bottoms_Up','Bottoms Up','core','bodyweight','strength','beginner'),
('Box_Jump_Multiple_Response','Box Jump (Multiple Response)','legs','other','plyometrics','beginner')
ON CONFLICT (external_id) DO NOTHING;