INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Box_Skip','Box Skip','legs','other','plyometrics','beginner'),
('Box_Squat','Box Squat','legs','barbell','powerlifting','intermediate'),
('Box_Squat_with_Bands','Box Squat with Bands','legs','barbell','powerlifting','expert'),
('Box_Squat_with_Chains','Box Squat with Chains','legs','barbell','strength','expert'),
('Brachialis-SMR','Brachialis-SMR','arms','other','stretching','intermediate'),
('Bradford_Rocky_Presses','Bradford/Rocky Presses','shoulders','barbell','strength','beginner'),
('Butt-Ups','Butt-Ups','core','bodyweight','strength','beginner'),
('Butt_Lift_Bridge','Butt Lift (Bridge)','legs','bodyweight','strength','beginner'),
('Butterfly','Butterfly','chest','machine','strength','beginner'),
('Cable_Chest_Press','Cable Chest Press','chest','cable','strength','beginner'),
('Cable_Crossover','Cable Crossover','chest','cable','strength','beginner'),
('Cable_Crunch','Cable Crunch','core','cable','strength','beginner'),
('Cable_Deadlifts','Cable Deadlifts','legs','cable','strength','beginner'),
('Cable_Hammer_Curls_-_Rope_Attachment','Cable Hammer Curls - Rope Attachment','arms','cable','strength','beginner'),
('Cable_Hip_Adduction','Cable Hip Adduction','legs','cable','strength','beginner'),
('Cable_Incline_Pushdown','Cable Incline Pushdown','back','cable','strength','beginner'),
('Cable_Incline_Triceps_Extension','Cable Incline Triceps Extension','arms','cable','strength','beginner'),
('Cable_Internal_Rotation','Cable Internal Rotation','shoulders','cable','strength','beginner'),
('Cable_Iron_Cross','Cable Iron Cross','chest','cable','strength','beginner'),
('Cable_Judo_Flip','Cable Judo Flip','core','cable','strength','beginner'),
('Cable_Lying_Triceps_Extension','Cable Lying Triceps Extension','arms','cable','strength','beginner'),
('Cable_One_Arm_Tricep_Extension','Cable One Arm Tricep Extension','arms','cable','strength','beginner'),
('Cable_Preacher_Curl','Cable Preacher Curl','arms','cable','strength','beginner'),
('Cable_Rear_Delt_Fly','Cable Rear Delt Fly','shoulders','cable','strength','beginner'),
('Cable_Reverse_Crunch','Cable Reverse Crunch','core','cable','strength','beginner'),
('Cable_Rope_Overhead_Triceps_Extension','Cable Rope Overhead Triceps Extension','arms','cable','strength','beginner'),
('Cable_Rope_Rear-Delt_Rows','Cable Rope Rear-Delt Rows','shoulders','cable','strength','beginner'),
('Cable_Russian_Twists','Cable Russian Twists','core','cable','strength','beginner'),
('Cable_Seated_Crunch','Cable Seated Crunch','core','cable','strength','beginner'),
('Cable_Seated_Lateral_Raise','Cable Seated Lateral Raise','shoulders','cable','strength','beginner'),
('Cable_Shoulder_Press','Cable Shoulder Press','shoulders','cable','strength','beginner'),
('Cable_Shrugs','Cable Shrugs','back','cable','strength','beginner'),
('Cable_Wrist_Curl','Cable Wrist Curl','arms','cable','strength','beginner'),
('Calf-Machine_Shoulder_Shrug','Calf-Machine Shoulder Shrug','back','machine','strength','beginner'),
('Calf_Press','Calf Press','legs','machine','strength','beginner'),
('Calf_Press_On_The_Leg_Press_Machine','Calf Press On The Leg Press Machine','legs','machine','strength','beginner'),
('Calf_Raise_On_A_Dumbbell','Calf Raise On A Dumbbell','legs','dumbbell','strength','intermediate'),
('Calf_Raises_-_With_Bands','Calf Raises - With Bands','legs','bands','strength','beginner'),
('Calf_Stretch_Elbows_Against_Wall','Calf Stretch Elbows Against Wall','legs','other','stretching','beginner'),
('Calf_Stretch_Hands_Against_Wall','Calf Stretch Hands Against Wall','legs','other','stretching','beginner'),
('Calves-SMR','Calves-SMR','legs','other','stretching','intermediate'),
('Car_Deadlift','Car Deadlift','legs','other','strongman','intermediate'),
('Car_Drivers','Car Drivers','shoulders','barbell','strength','beginner'),
('Carioca_Quick_Step','Carioca Quick Step','legs','other','plyometrics','beginner'),
('Cat_Stretch','Cat Stretch','back','other','stretching','beginner'),
('Catch_and_Overhead_Throw','Catch and Overhead Throw','back','other','plyometrics','beginner'),
('Chain_Handle_Extension','Chain Handle Extension','arms','other','powerlifting','intermediate'),
('Chain_Press','Chain Press','chest','other','powerlifting','intermediate'),
('Chair_Leg_Extended_Stretch','Chair Leg Extended Stretch','legs','other','stretching','beginner'),
('Chair_Lower_Back_Stretch','Chair Lower Back Stretch','back','other','stretching','beginner')
ON CONFLICT (external_id) DO NOTHING;