INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Chair_Squat','Chair Squat','legs','machine','strength','beginner'),
('Chair_Upper_Body_Stretch','Chair Upper Body Stretch','shoulders','other','stretching','beginner'),
('Chest_And_Front_Of_Shoulder_Stretch','Chest And Front Of Shoulder Stretch','chest','other','stretching','beginner'),
('Chest_Push_from_3_point_stance','Chest Push from 3 point stance','chest','other','plyometrics','beginner'),
('Chest_Push_multiple_response','Chest Push (multiple response)','chest','other','plyometrics','beginner'),
('Chest_Push_single_response','Chest Push (single response)','chest','other','plyometrics','beginner'),
('Chest_Push_with_Run_Release','Chest Push with Run Release','chest','other','plyometrics','beginner'),
('Chest_Stretch_on_Stability_Ball','Chest Stretch on Stability Ball','chest','other','stretching','beginner'),
('Childs_Pose','Child''s Pose','back','other','stretching','beginner'),
('Chin-Up','Chin-Up','back','bodyweight','strength','beginner'),
('Chin_To_Chest_Stretch','Chin To Chest Stretch','other','other','stretching','beginner'),
('Circus_Bell','Circus Bell','shoulders','other','strongman','expert'),
('Clean','Clean','legs','barbell','olympic weightlifting','intermediate'),
('Clean_Deadlift','Clean Deadlift','legs','barbell','olympic weightlifting','beginner'),
('Clean_Pull','Clean Pull','legs','barbell','olympic weightlifting','intermediate'),
('Clean_Shrug','Clean Shrug','back','barbell','olympic weightlifting','beginner'),
('Clean_and_Jerk','Clean and Jerk','shoulders','barbell','olympic weightlifting','expert'),
('Clean_and_Press','Clean and Press','shoulders','barbell','strength','intermediate'),
('Clean_from_Blocks','Clean from Blocks','legs','barbell','olympic weightlifting','intermediate'),
('Clock_Push-Up','Clock Push-Up','chest','bodyweight','strength','intermediate'),
('Close-Grip_Barbell_Bench_Press','Close-Grip Barbell Bench Press','arms','barbell','strength','beginner'),
('Close-Grip_Dumbbell_Press','Close-Grip Dumbbell Press','arms','dumbbell','strength','beginner'),
('Close-Grip_EZ-Bar_Curl_with_Band','Close-Grip EZ-Bar Curl with Band','arms','barbell','strength','beginner'),
('Close-Grip_EZ-Bar_Press','Close-Grip EZ-Bar Press','arms','barbell','strength','beginner'),
('Close-Grip_EZ_Bar_Curl','Close-Grip EZ Bar Curl','arms','barbell','strength','beginner'),
('Close-Grip_Front_Lat_Pulldown','Close-Grip Front Lat Pulldown','back','cable','strength','beginner'),
('Close-Grip_Push-Up_off_of_a_Dumbbell','Close-Grip Push-Up off of a Dumbbell','arms','bodyweight','strength','intermediate'),
('Close-Grip_Standing_Barbell_Curl','Close-Grip Standing Barbell Curl','arms','barbell','strength','beginner'),
('Cocoons','Cocoons','core','bodyweight','strength','beginner'),
('Conans_Wheel','Conan''s Wheel','legs','other','strongman','intermediate'),
('Concentration_Curls','Concentration Curls','arms','dumbbell','strength','beginner'),
('Cross-Body_Crunch','Cross-Body Crunch','core','bodyweight','strength','beginner'),
('Cross_Body_Hammer_Curl','Cross Body Hammer Curl','arms','dumbbell','strength','beginner'),
('Cross_Over_-_With_Bands','Cross Over - With Bands','chest','bands','strength','beginner'),
('Crossover_Reverse_Lunge','Crossover Reverse Lunge','back','other','stretching','intermediate'),
('Crucifix','Crucifix','shoulders','other','strongman','beginner'),
('Crunch_-_Hands_Overhead','Crunch - Hands Overhead','core','bodyweight','strength','beginner'),
('Crunch_-_Legs_On_Exercise_Ball','Crunch - Legs On Exercise Ball','core','bodyweight','strength','beginner'),
('Crunches','Crunches','core','bodyweight','strength','beginner'),
('Cuban_Press','Cuban Press','shoulders','dumbbell','strength','intermediate'),
('Dancers_Stretch','Dancer''s Stretch','back','other','stretching','beginner'),
('Dead_Bug','Dead Bug','core','bodyweight','strength','beginner'),
('Deadlift_with_Bands','Deadlift with Bands','back','barbell','powerlifting','expert'),
('Deadlift_with_Chains','Deadlift with Chains','back','barbell','powerlifting','expert'),
('Decline_Barbell_Bench_Press','Decline Barbell Bench Press','chest','barbell','strength','beginner'),
('Decline_Close-Grip_Bench_To_Skull_Crusher','Decline Close-Grip Bench To Skull Crusher','arms','barbell','strength','intermediate'),
('Decline_Crunch','Decline Crunch','core','bodyweight','strength','intermediate'),
('Decline_Dumbbell_Bench_Press','Decline Dumbbell Bench Press','chest','dumbbell','strength','beginner'),
('Decline_Dumbbell_Flyes','Decline Dumbbell Flyes','chest','dumbbell','strength','beginner'),
('Decline_Dumbbell_Triceps_Extension','Decline Dumbbell Triceps Extension','arms','dumbbell','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;