INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Decline_EZ_Bar_Triceps_Extension','Decline EZ Bar Triceps Extension','arms','barbell','strength','beginner'),
('Decline_Oblique_Crunch','Decline Oblique Crunch','core','bodyweight','strength','beginner'),
('Decline_Push-Up','Decline Push-Up','chest','other','strength','beginner'),
('Decline_Reverse_Crunch','Decline Reverse Crunch','core','bodyweight','strength','beginner'),
('Decline_Smith_Press','Decline Smith Press','chest','machine','strength','beginner'),
('Deficit_Deadlift','Deficit Deadlift','back','barbell','powerlifting','intermediate'),
('Depth_Jump_Leap','Depth Jump Leap','legs','other','plyometrics','beginner'),
('Dip_Machine','Dip Machine','arms','machine','strength','beginner'),
('Dips_-_Chest_Version','Dips - Chest Version','chest','other','strength','intermediate'),
('Dips_-_Triceps_Version','Dips - Triceps Version','arms','bodyweight','strength','beginner'),
('Donkey_Calf_Raises','Donkey Calf Raises','legs','other','strength','intermediate'),
('Double_Kettlebell_Alternating_Hang_Clean','Double Kettlebell Alternating Hang Clean','legs','kettlebell','strength','intermediate'),
('Double_Kettlebell_Jerk','Double Kettlebell Jerk','shoulders','kettlebell','strength','intermediate'),
('Double_Kettlebell_Push_Press','Double Kettlebell Push Press','shoulders','kettlebell','strength','intermediate'),
('Double_Kettlebell_Snatch','Double Kettlebell Snatch','shoulders','kettlebell','strength','expert'),
('Double_Kettlebell_Windmill','Double Kettlebell Windmill','core','kettlebell','strength','intermediate'),
('Double_Leg_Butt_Kick','Double Leg Butt Kick','legs','bodyweight','plyometrics','beginner'),
('Downward_Facing_Balance','Downward Facing Balance','legs','other','strength','intermediate'),
('Drag_Curl','Drag Curl','arms','barbell','strength','intermediate'),
('Drop_Push','Drop Push','chest','other','plyometrics','intermediate'),
('Dumbbell_Alternate_Bicep_Curl','Dumbbell Alternate Bicep Curl','arms','dumbbell','strength','beginner'),
('Dumbbell_Bench_Press','Dumbbell Bench Press','chest','dumbbell','strength','beginner'),
('Dumbbell_Bench_Press_with_Neutral_Grip','Dumbbell Bench Press with Neutral Grip','chest','dumbbell','strength','beginner'),
('Dumbbell_Bicep_Curl','Dumbbell Bicep Curl','arms','dumbbell','strength','beginner'),
('Dumbbell_Clean','Dumbbell Clean','legs','dumbbell','strength','intermediate'),
('Dumbbell_Floor_Press','Dumbbell Floor Press','arms','dumbbell','powerlifting','intermediate'),
('Dumbbell_Flyes','Dumbbell Flyes','chest','dumbbell','strength','beginner'),
('Dumbbell_Incline_Row','Dumbbell Incline Row','back','dumbbell','strength','beginner'),
('Dumbbell_Incline_Shoulder_Raise','Dumbbell Incline Shoulder Raise','shoulders','dumbbell','strength','beginner'),
('Dumbbell_Lunges','Dumbbell Lunges','legs','dumbbell','strength','beginner'),
('Dumbbell_Lying_One-Arm_Rear_Lateral_Raise','Dumbbell Lying One-Arm Rear Lateral Raise','shoulders','dumbbell','strength','intermediate'),
('Dumbbell_Lying_Pronation','Dumbbell Lying Pronation','arms','dumbbell','strength','intermediate'),
('Dumbbell_Lying_Rear_Lateral_Raise','Dumbbell Lying Rear Lateral Raise','shoulders','dumbbell','strength','intermediate'),
('Dumbbell_Lying_Supination','Dumbbell Lying Supination','arms','dumbbell','strength','intermediate'),
('Dumbbell_One-Arm_Shoulder_Press','Dumbbell One-Arm Shoulder Press','shoulders','dumbbell','strength','intermediate'),
('Dumbbell_One-Arm_Triceps_Extension','Dumbbell One-Arm Triceps Extension','arms','dumbbell','strength','intermediate'),
('Dumbbell_One-Arm_Upright_Row','Dumbbell One-Arm Upright Row','shoulders','dumbbell','strength','intermediate'),
('Dumbbell_Prone_Incline_Curl','Dumbbell Prone Incline Curl','arms','dumbbell','strength','intermediate'),
('Dumbbell_Raise','Dumbbell Raise','shoulders','dumbbell','strength','beginner'),
('Dumbbell_Rear_Lunge','Dumbbell Rear Lunge','legs','dumbbell','strength','intermediate'),
('Dumbbell_Scaption','Dumbbell Scaption','shoulders','dumbbell','strength','beginner'),
('Dumbbell_Seated_Box_Jump','Dumbbell Seated Box Jump','legs','dumbbell','plyometrics','intermediate'),
('Dumbbell_Seated_One-Leg_Calf_Raise','Dumbbell Seated One-Leg Calf Raise','legs','dumbbell','strength','beginner'),
('Dumbbell_Shoulder_Press','Dumbbell Shoulder Press','shoulders','dumbbell','strength','intermediate'),
('Dumbbell_Shrug','Dumbbell Shrug','back','dumbbell','strength','beginner'),
('Dumbbell_Side_Bend','Dumbbell Side Bend','core','dumbbell','strength','beginner'),
('Dumbbell_Squat','Dumbbell Squat','legs','dumbbell','strength','beginner'),
('Dumbbell_Squat_To_A_Bench','Dumbbell Squat To A Bench','legs','dumbbell','strength','intermediate'),
('Dumbbell_Step_Ups','Dumbbell Step Ups','legs','dumbbell','strength','intermediate'),
('Dumbbell_Tricep_Extension_-Pronated_Grip','Dumbbell Tricep Extension -Pronated Grip','arms','dumbbell','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;