INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Dynamic_Back_Stretch','Dynamic Back Stretch','back','other','stretching','beginner'),
('Dynamic_Chest_Stretch','Dynamic Chest Stretch','chest','other','stretching','beginner'),
('EZ-Bar_Curl','EZ-Bar Curl','arms','barbell','strength','beginner'),
('EZ-Bar_Skullcrusher','EZ-Bar Skullcrusher','arms','barbell','strength','beginner'),
('Elbow_Circles','Elbow Circles','shoulders','other','stretching','beginner'),
('Elbow_to_Knee','Elbow to Knee','core','bodyweight','strength','beginner'),
('Elbows_Back','Elbows Back','chest','other','stretching','beginner'),
('Elevated_Back_Lunge','Elevated Back Lunge','legs','barbell','strength','intermediate'),
('Elevated_Cable_Rows','Elevated Cable Rows','back','cable','strength','intermediate'),
('Elliptical_Trainer','Elliptical Trainer','legs','machine','cardio','intermediate'),
('Exercise_Ball_Crunch','Exercise Ball Crunch','core','other','strength','beginner'),
('Exercise_Ball_Pull-In','Exercise Ball Pull-In','core','other','strength','beginner'),
('Extended_Range_One-Arm_Kettlebell_Floor_Press','Extended Range One-Arm Kettlebell Floor Press','chest','kettlebell','strength','beginner'),
('External_Rotation','External Rotation','shoulders','dumbbell','strength','beginner'),
('External_Rotation_with_Band','External Rotation with Band','shoulders','bands','strength','beginner'),
('External_Rotation_with_Cable','External Rotation with Cable','shoulders','cable','strength','beginner'),
('Face_Pull','Face Pull','shoulders','cable','strength','intermediate'),
('Farmers_Walk','Farmer''s Walk','arms','other','strongman','intermediate'),
('Fast_Skipping','Fast Skipping','legs','bodyweight','plyometrics','beginner'),
('Finger_Curls','Finger Curls','arms','barbell','strength','beginner'),
('Flat_Bench_Cable_Flyes','Flat Bench Cable Flyes','chest','cable','strength','intermediate'),
('Flat_Bench_Leg_Pull-In','Flat Bench Leg Pull-In','core','bodyweight','strength','beginner'),
('Flat_Bench_Lying_Leg_Raise','Flat Bench Lying Leg Raise','core','bodyweight','strength','beginner'),
('Flexor_Incline_Dumbbell_Curls','Flexor Incline Dumbbell Curls','arms','dumbbell','strength','beginner'),
('Floor_Glute-Ham_Raise','Floor Glute-Ham Raise','legs','other','strength','intermediate'),
('Floor_Press','Floor Press','arms','barbell','powerlifting','intermediate'),
('Floor_Press_with_Chains','Floor Press with Chains','arms','barbell','powerlifting','intermediate'),
('Flutter_Kicks','Flutter Kicks','legs','bodyweight','strength','beginner'),
('Foot-SMR','Foot-SMR','legs','other','stretching','intermediate'),
('Forward_Drag_with_Press','Forward Drag with Press','chest','other','strongman','intermediate'),
('Frankenstein_Squat','Frankenstein Squat','legs','barbell','olympic weightlifting','intermediate'),
('Freehand_Jump_Squat','Freehand Jump Squat','legs','bodyweight','strength','intermediate'),
('Frog_Hops','Frog Hops','legs','other','stretching','intermediate'),
('Frog_Sit-Ups','Frog Sit-Ups','core','bodyweight','strength','intermediate'),
('Front_Barbell_Squat','Front Barbell Squat','legs','barbell','strength','expert'),
('Front_Barbell_Squat_To_A_Bench','Front Barbell Squat To A Bench','legs','barbell','strength','expert'),
('Front_Box_Jump','Front Box Jump','legs','other','plyometrics','beginner'),
('Front_Cable_Raise','Front Cable Raise','shoulders','cable','strength','beginner'),
('Front_Cone_Hops_or_hurdle_hops','Front Cone Hops (or hurdle hops)','legs','other','plyometrics','beginner'),
('Front_Dumbbell_Raise','Front Dumbbell Raise','shoulders','dumbbell','strength','beginner'),
('Front_Incline_Dumbbell_Raise','Front Incline Dumbbell Raise','shoulders','dumbbell','strength','beginner'),
('Front_Leg_Raises','Front Leg Raises','legs','bodyweight','stretching','beginner'),
('Front_Plate_Raise','Front Plate Raise','shoulders','other','strength','intermediate'),
('Front_Raise_And_Pullover','Front Raise And Pullover','chest','barbell','strength','beginner'),
('Front_Squat_Clean_Grip','Front Squat (Clean Grip)','legs','barbell','strength','intermediate'),
('Front_Squats_With_Two_Kettlebells','Front Squats With Two Kettlebells','legs','kettlebell','strength','intermediate'),
('Front_Two-Dumbbell_Raise','Front Two-Dumbbell Raise','shoulders','dumbbell','strength','beginner'),
('Full_Range-Of-Motion_Lat_Pulldown','Full Range-Of-Motion Lat Pulldown','back','cable','strength','intermediate'),
('Gironda_Sternum_Chins','Gironda Sternum Chins','back','other','strength','intermediate'),
('Glute_Ham_Raise','Glute Ham Raise','legs','machine','powerlifting','intermediate')
ON CONFLICT (external_id) DO NOTHING;