INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Glute_Kickback','Glute Kickback','legs','bodyweight','strength','beginner'),
('Goblet_Squat','Goblet Squat','legs','kettlebell','strength','beginner'),
('Good_Morning','Good Morning','legs','barbell','powerlifting','intermediate'),
('Good_Morning_off_Pins','Good Morning off Pins','legs','barbell','powerlifting','intermediate'),
('Gorilla_Chin_Crunch','Gorilla Chin/Crunch','core','bodyweight','strength','intermediate'),
('Groin_and_Back_Stretch','Groin and Back Stretch','legs','other','stretching','intermediate'),
('Groiners','Groiners','legs','bodyweight','stretching','intermediate'),
('Hack_Squat','Hack Squat','legs','machine','strength','beginner'),
('Hammer_Curls','Hammer Curls','arms','dumbbell','strength','beginner'),
('Hammer_Grip_Incline_DB_Bench_Press','Hammer Grip Incline DB Bench Press','chest','dumbbell','strength','beginner'),
('Hamstring-SMR','Hamstring-SMR','legs','other','stretching','beginner'),
('Hamstring_Stretch','Hamstring Stretch','legs','other','stretching','beginner'),
('Handstand_Push-Ups','Handstand Push-Ups','shoulders','bodyweight','strength','expert'),
('Hang_Clean','Hang Clean','legs','barbell','olympic weightlifting','intermediate'),
('Hang_Clean_-_Below_the_Knees','Hang Clean - Below the Knees','legs','barbell','olympic weightlifting','intermediate'),
('Hang_Snatch','Hang Snatch','legs','barbell','olympic weightlifting','expert'),
('Hang_Snatch_-_Below_Knees','Hang Snatch - Below Knees','legs','barbell','olympic weightlifting','expert'),
('Hanging_Bar_Good_Morning','Hanging Bar Good Morning','legs','barbell','powerlifting','intermediate'),
('Hanging_Leg_Raise','Hanging Leg Raise','core','bodyweight','strength','expert'),
('Hanging_Pike','Hanging Pike','core','bodyweight','strength','expert'),
('Heaving_Snatch_Balance','Heaving Snatch Balance','legs','barbell','olympic weightlifting','intermediate'),
('Heavy_Bag_Thrust','Heavy Bag Thrust','chest','other','plyometrics','beginner'),
('High_Cable_Curls','High Cable Curls','arms','cable','strength','intermediate'),
('Hip_Circles_prone','Hip Circles (prone)','legs','bodyweight','stretching','beginner'),
('Hip_Extension_with_Bands','Hip Extension with Bands','legs','bands','strength','beginner'),
('Hip_Flexion_with_Band','Hip Flexion with Band','legs','bands','strength','beginner'),
('Hip_Lift_with_Band','Hip Lift with Band','legs','bands','powerlifting','beginner'),
('Hug_A_Ball','Hug A Ball','back','other','stretching','beginner'),
('Hug_Knees_To_Chest','Hug Knees To Chest','back','other','stretching','beginner'),
('Hurdle_Hops','Hurdle Hops','legs','other','plyometrics','beginner'),
('Hyperextensions_Back_Extensions','Hyperextensions (Back Extensions)','back','other','strength','beginner'),
('Hyperextensions_With_No_Hyperextension_Bench','Hyperextensions With No Hyperextension Bench','back','bodyweight','strength','intermediate'),
('IT_Band_and_Glute_Stretch','IT Band and Glute Stretch','legs','other','stretching','intermediate'),
('Iliotibial_Tract-SMR','Iliotibial Tract-SMR','legs','other','stretching','intermediate'),
('Inchworm','Inchworm','legs','bodyweight','stretching','beginner'),
('Incline_Barbell_Triceps_Extension','Incline Barbell Triceps Extension','arms','barbell','strength','intermediate'),
('Incline_Bench_Pull','Incline Bench Pull','back','barbell','strength','beginner'),
('Incline_Cable_Chest_Press','Incline Cable Chest Press','chest','cable','strength','beginner'),
('Incline_Cable_Flye','Incline Cable Flye','chest','cable','strength','intermediate'),
('Incline_Dumbbell_Bench_With_Palms_Facing_In','Incline Dumbbell Bench With Palms Facing In','chest','dumbbell','strength','beginner'),
('Incline_Dumbbell_Curl','Incline Dumbbell Curl','arms','dumbbell','strength','beginner'),
('Incline_Dumbbell_Flyes','Incline Dumbbell Flyes','chest','dumbbell','strength','beginner'),
('Incline_Dumbbell_Flyes_-_With_A_Twist','Incline Dumbbell Flyes - With A Twist','chest','dumbbell','strength','beginner'),
('Incline_Dumbbell_Press','Incline Dumbbell Press','chest','dumbbell','strength','beginner'),
('Incline_Hammer_Curls','Incline Hammer Curls','arms','dumbbell','strength','beginner'),
('Incline_Inner_Biceps_Curl','Incline Inner Biceps Curl','arms','dumbbell','strength','beginner'),
('Incline_Push-Up','Incline Push-Up','chest','bodyweight','strength','beginner'),
('Incline_Push-Up_Close-Grip','Incline Push-Up Close-Grip','arms','bodyweight','strength','beginner'),
('Incline_Push-Up_Depth_Jump','Incline Push-Up Depth Jump','chest','other','plyometrics','beginner'),
('Incline_Push-Up_Medium','Incline Push-Up Medium','chest','bodyweight','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;