INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Incline_Push-Up_Reverse_Grip','Incline Push-Up Reverse Grip','chest','bodyweight','strength','beginner'),
('Incline_Push-Up_Wide','Incline Push-Up Wide','chest','bodyweight','strength','beginner'),
('Intermediate_Groin_Stretch','Intermediate Groin Stretch','legs','other','stretching','intermediate'),
('Intermediate_Hip_Flexor_and_Quad_Stretch','Intermediate Hip Flexor and Quad Stretch','legs','other','stretching','intermediate'),
('Internal_Rotation_with_Band','Internal Rotation with Band','shoulders','bands','strength','beginner'),
('Inverted_Row','Inverted Row','back','other','strength','beginner'),
('Inverted_Row_with_Straps','Inverted Row with Straps','back','other','strength','beginner'),
('Iron_Cross','Iron Cross','shoulders','dumbbell','strength','intermediate'),
('Iron_Crosses_stretch','Iron Crosses (stretch)','legs','other','stretching','intermediate'),
('Isometric_Chest_Squeezes','Isometric Chest Squeezes','chest','bodyweight','plyometrics','beginner'),
('Isometric_Neck_Exercise_-_Front_And_Back','Isometric Neck Exercise - Front And Back','other','bodyweight','strength','beginner'),
('Isometric_Neck_Exercise_-_Sides','Isometric Neck Exercise - Sides','other','bodyweight','strength','beginner'),
('Isometric_Wipers','Isometric Wipers','chest','bodyweight','strength','beginner'),
('JM_Press','JM Press','arms','barbell','strength','beginner'),
('Jackknife_Sit-Up','Jackknife Sit-Up','core','bodyweight','strength','beginner'),
('Janda_Sit-Up','Janda Sit-Up','core','bodyweight','strength','beginner'),
('Jefferson_Squats','Jefferson Squats','legs','barbell','strength','intermediate'),
('Jerk_Balance','Jerk Balance','shoulders','barbell','olympic weightlifting','intermediate'),
('Jerk_Dip_Squat','Jerk Dip Squat','legs','barbell','olympic weightlifting','intermediate'),
('Jogging_Treadmill','Jogging, Treadmill','legs','machine','cardio','beginner'),
('Keg_Load','Keg Load','back','other','strongman','intermediate'),
('Kettlebell_Arnold_Press','Kettlebell Arnold Press','shoulders','kettlebell','strength','intermediate'),
('Kettlebell_Dead_Clean','Kettlebell Dead Clean','legs','kettlebell','strength','intermediate'),
('Kettlebell_Figure_8','Kettlebell Figure 8','core','kettlebell','strength','intermediate'),
('Kettlebell_Hang_Clean','Kettlebell Hang Clean','legs','kettlebell','strength','intermediate'),
('Kettlebell_One-Legged_Deadlift','Kettlebell One-Legged Deadlift','legs','kettlebell','strength','intermediate'),
('Kettlebell_Pass_Between_The_Legs','Kettlebell Pass Between The Legs','core','kettlebell','strength','intermediate'),
('Kettlebell_Pirate_Ships','Kettlebell Pirate Ships','shoulders','kettlebell','strength','beginner'),
('Kettlebell_Pistol_Squat','Kettlebell Pistol Squat','legs','kettlebell','strength','expert'),
('Kettlebell_Seated_Press','Kettlebell Seated Press','shoulders','kettlebell','strength','intermediate'),
('Kettlebell_Seesaw_Press','Kettlebell Seesaw Press','shoulders','kettlebell','strength','intermediate'),
('Kettlebell_Sumo_High_Pull','Kettlebell Sumo High Pull','back','kettlebell','strength','intermediate'),
('Kettlebell_Thruster','Kettlebell Thruster','shoulders','kettlebell','strength','intermediate'),
('Kettlebell_Turkish_Get-Up_Lunge_style','Kettlebell Turkish Get-Up (Lunge style)','shoulders','kettlebell','strength','intermediate'),
('Kettlebell_Turkish_Get-Up_Squat_style','Kettlebell Turkish Get-Up (Squat style)','shoulders','kettlebell','strength','intermediate'),
('Kettlebell_Windmill','Kettlebell Windmill','core','kettlebell','strength','intermediate'),
('Kipping_Muscle_Up','Kipping Muscle Up','back','other','strength','intermediate'),
('Knee_Across_The_Body','Knee Across The Body','legs','other','stretching','beginner'),
('Knee_Circles','Knee Circles','legs','bodyweight','stretching','beginner'),
('Knee_Hip_Raise_On_Parallel_Bars','Knee/Hip Raise On Parallel Bars','core','other','strength','beginner'),
('Knee_Tuck_Jump','Knee Tuck Jump','legs','bodyweight','plyometrics','beginner'),
('Kneeling_Arm_Drill','Kneeling Arm Drill','shoulders','other','plyometrics','beginner'),
('Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists','Kneeling Cable Crunch With Alternating Oblique Twists','core','cable','strength','beginner'),
('Kneeling_Cable_Triceps_Extension','Kneeling Cable Triceps Extension','arms','cable','strength','intermediate'),
('Kneeling_Forearm_Stretch','Kneeling Forearm Stretch','arms','other','stretching','beginner'),
('Kneeling_High_Pulley_Row','Kneeling High Pulley Row','back','cable','strength','beginner'),
('Kneeling_Hip_Flexor','Kneeling Hip Flexor','legs','other','stretching','beginner'),
('Kneeling_Jump_Squat','Kneeling Jump Squat','legs','barbell','olympic weightlifting','expert'),
('Kneeling_Single-Arm_High_Pulley_Row','Kneeling Single-Arm High Pulley Row','back','cable','strength','beginner'),
('Kneeling_Squat','Kneeling Squat','legs','barbell','powerlifting','intermediate')
ON CONFLICT (external_id) DO NOTHING;