INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Landmine_180s','Landmine 180''s','core','barbell','strength','beginner'),
('Landmine_Linear_Jammer','Landmine Linear Jammer','shoulders','barbell','strength','intermediate'),
('Lateral_Bound','Lateral Bound','legs','bodyweight','plyometrics','beginner'),
('Lateral_Box_Jump','Lateral Box Jump','legs','other','plyometrics','beginner'),
('Lateral_Cone_Hops','Lateral Cone Hops','legs','other','plyometrics','beginner'),
('Lateral_Raise_-_With_Bands','Lateral Raise - With Bands','shoulders','bands','strength','beginner'),
('Latissimus_Dorsi-SMR','Latissimus Dorsi-SMR','back','other','stretching','beginner'),
('Leg-Over_Floor_Press','Leg-Over Floor Press','chest','kettlebell','strength','intermediate'),
('Leg-Up_Hamstring_Stretch','Leg-Up Hamstring Stretch','legs','other','stretching','beginner'),
('Leg_Extensions','Leg Extensions','legs','machine','strength','beginner'),
('Leg_Lift','Leg Lift','legs','bodyweight','strength','beginner'),
('Leg_Press','Leg Press','legs','machine','strength','beginner'),
('Leg_Pull-In','Leg Pull-In','core','bodyweight','strength','beginner'),
('Leverage_Chest_Press','Leverage Chest Press','chest','machine','strength','beginner'),
('Leverage_Deadlift','Leverage Deadlift','legs','machine','strength','beginner'),
('Leverage_Decline_Chest_Press','Leverage Decline Chest Press','chest','machine','strength','beginner'),
('Leverage_High_Row','Leverage High Row','back','machine','strength','beginner'),
('Leverage_Incline_Chest_Press','Leverage Incline Chest Press','chest','machine','strength','beginner'),
('Leverage_Iso_Row','Leverage Iso Row','back','machine','strength','beginner'),
('Leverage_Shoulder_Press','Leverage Shoulder Press','shoulders','machine','strength','beginner'),
('Leverage_Shrug','Leverage Shrug','back','machine','strength','beginner'),
('Linear_3-Part_Start_Technique','Linear 3-Part Start Technique','legs','other','plyometrics','beginner'),
('Linear_Acceleration_Wall_Drill','Linear Acceleration Wall Drill','legs','other','plyometrics','beginner'),
('Linear_Depth_Jump','Linear Depth Jump','legs','other','plyometrics','intermediate'),
('Log_Lift','Log Lift','shoulders','other','strongman','intermediate'),
('London_Bridges','London Bridges','back','other','strength','intermediate'),
('Looking_At_Ceiling','Looking At Ceiling','legs','other','stretching','beginner'),
('Low_Cable_Crossover','Low Cable Crossover','chest','cable','strength','beginner'),
('Low_Cable_Triceps_Extension','Low Cable Triceps Extension','arms','cable','strength','beginner'),
('Low_Pulley_Row_To_Neck','Low Pulley Row To Neck','shoulders','cable','strength','beginner'),
('Lower_Back-SMR','Lower Back-SMR','back','other','stretching','beginner'),
('Lower_Back_Curl','Lower Back Curl','core','bodyweight','stretching','beginner'),
('Lunge_Pass_Through','Lunge Pass Through','legs','kettlebell','strength','intermediate'),
('Lunge_Sprint','Lunge Sprint','legs','machine','strength','intermediate'),
('Lying_Bent_Leg_Groin','Lying Bent Leg Groin','legs','other','stretching','expert'),
('Lying_Cable_Curl','Lying Cable Curl','arms','cable','strength','intermediate'),
('Lying_Cambered_Barbell_Row','Lying Cambered Barbell Row','back','barbell','strength','beginner'),
('Lying_Close-Grip_Bar_Curl_On_High_Pulley','Lying Close-Grip Bar Curl On High Pulley','arms','cable','strength','beginner'),
('Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head','Lying Close-Grip Barbell Triceps Extension Behind The Head','arms','barbell','strength','intermediate'),
('Lying_Close-Grip_Barbell_Triceps_Press_To_Chin','Lying Close-Grip Barbell Triceps Press To Chin','arms','barbell','strength','intermediate'),
('Lying_Crossover','Lying Crossover','legs','bodyweight','stretching','expert'),
('Lying_Dumbbell_Tricep_Extension','Lying Dumbbell Tricep Extension','arms','dumbbell','strength','intermediate'),
('Lying_Face_Down_Plate_Neck_Resistance','Lying Face Down Plate Neck Resistance','other','other','strength','intermediate'),
('Lying_Face_Up_Plate_Neck_Resistance','Lying Face Up Plate Neck Resistance','other','other','strength','intermediate'),
('Lying_Glute','Lying Glute','legs','bodyweight','stretching','expert'),
('Lying_Hamstring','Lying Hamstring','legs','other','stretching','expert'),
('Lying_High_Bench_Barbell_Curl','Lying High Bench Barbell Curl','arms','barbell','strength','intermediate'),
('Lying_Leg_Curls','Lying Leg Curls','legs','machine','strength','beginner'),
('Lying_Machine_Squat','Lying Machine Squat','legs','machine','strength','intermediate'),
('Lying_One-Arm_Lateral_Raise','Lying One-Arm Lateral Raise','shoulders','dumbbell','strength','intermediate')
ON CONFLICT (external_id) DO NOTHING;