INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Lying_Prone_Quadriceps','Lying Prone Quadriceps','legs','bodyweight','stretching','expert'),
('Lying_Rear_Delt_Raise','Lying Rear Delt Raise','shoulders','dumbbell','strength','intermediate'),
('Lying_Supine_Dumbbell_Curl','Lying Supine Dumbbell Curl','arms','dumbbell','strength','beginner'),
('Lying_T-Bar_Row','Lying T-Bar Row','back','machine','strength','intermediate'),
('Lying_Triceps_Press','Lying Triceps Press','arms','barbell','strength','intermediate'),
('Machine_Bench_Press','Machine Bench Press','chest','machine','strength','beginner'),
('Machine_Bicep_Curl','Machine Bicep Curl','arms','machine','strength','beginner'),
('Machine_Preacher_Curls','Machine Preacher Curls','arms','machine','strength','beginner'),
('Machine_Shoulder_Military_Press','Machine Shoulder (Military) Press','shoulders','machine','strength','beginner'),
('Machine_Triceps_Extension','Machine Triceps Extension','arms','machine','strength','beginner'),
('Medicine_Ball_Chest_Pass','Medicine Ball Chest Pass','chest','other','plyometrics','beginner'),
('Medicine_Ball_Full_Twist','Medicine Ball Full Twist','core','other','plyometrics','beginner'),
('Medicine_Ball_Scoop_Throw','Medicine Ball Scoop Throw','shoulders','other','plyometrics','beginner'),
('Middle_Back_Shrug','Middle Back Shrug','back','dumbbell','strength','intermediate'),
('Middle_Back_Stretch','Middle Back Stretch','back','other','stretching','beginner'),
('Mixed_Grip_Chin','Mixed Grip Chin','back','other','strength','expert'),
('Monster_Walk','Monster Walk','legs','bands','strength','beginner'),
('Mountain_Climbers','Mountain Climbers','legs','other','plyometrics','beginner'),
('Moving_Claw_Series','Moving Claw Series','legs','other','plyometrics','beginner'),
('Muscle_Snatch','Muscle Snatch','legs','barbell','olympic weightlifting','intermediate'),
('Muscle_Up','Muscle Up','back','other','strength','intermediate'),
('Narrow_Stance_Hack_Squats','Narrow Stance Hack Squats','legs','machine','strength','intermediate'),
('Narrow_Stance_Leg_Press','Narrow Stance Leg Press','legs','machine','strength','intermediate'),
('Narrow_Stance_Squats','Narrow Stance Squats','legs','barbell','strength','intermediate'),
('Natural_Glute_Ham_Raise','Natural Glute Ham Raise','legs','bodyweight','strength','intermediate'),
('Neck-SMR','Neck-SMR','other','other','stretching','intermediate'),
('Neck_Press','Neck Press','chest','barbell','strength','intermediate'),
('Oblique_Crunches','Oblique Crunches','core','bodyweight','strength','beginner'),
('Oblique_Crunches_-_On_The_Floor','Oblique Crunches - On The Floor','core','bodyweight','strength','beginner'),
('Olympic_Squat','Olympic Squat','legs','barbell','olympic weightlifting','intermediate'),
('On-Your-Back_Quad_Stretch','On-Your-Back Quad Stretch','legs','other','stretching','beginner'),
('On_Your_Side_Quad_Stretch','On Your Side Quad Stretch','legs','other','stretching','beginner'),
('One-Arm_Dumbbell_Row','One-Arm Dumbbell Row','back','dumbbell','strength','beginner'),
('One-Arm_Flat_Bench_Dumbbell_Flye','One-Arm Flat Bench Dumbbell Flye','chest','dumbbell','strength','beginner'),
('One-Arm_High-Pulley_Cable_Side_Bends','One-Arm High-Pulley Cable Side Bends','core','cable','strength','beginner'),
('One-Arm_Incline_Lateral_Raise','One-Arm Incline Lateral Raise','shoulders','dumbbell','strength','beginner'),
('One-Arm_Kettlebell_Clean','One-Arm Kettlebell Clean','legs','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Clean_and_Jerk','One-Arm Kettlebell Clean and Jerk','shoulders','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Floor_Press','One-Arm Kettlebell Floor Press','chest','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Jerk','One-Arm Kettlebell Jerk','shoulders','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Military_Press_To_The_Side','One-Arm Kettlebell Military Press To The Side','shoulders','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Para_Press','One-Arm Kettlebell Para Press','shoulders','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Push_Press','One-Arm Kettlebell Push Press','shoulders','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Row','One-Arm Kettlebell Row','back','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Snatch','One-Arm Kettlebell Snatch','shoulders','kettlebell','strength','expert'),
('One-Arm_Kettlebell_Split_Jerk','One-Arm Kettlebell Split Jerk','shoulders','kettlebell','strength','intermediate'),
('One-Arm_Kettlebell_Split_Snatch','One-Arm Kettlebell Split Snatch','shoulders','kettlebell','strength','expert'),
('One-Arm_Kettlebell_Swings','One-Arm Kettlebell Swings','legs','kettlebell','strength','intermediate'),
('One-Arm_Long_Bar_Row','One-Arm Long Bar Row','back','barbell','strength','beginner'),
('One-Arm_Medicine_Ball_Slam','One-Arm Medicine Ball Slam','core','other','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;