INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('One-Arm_Open_Palm_Kettlebell_Clean','One-Arm Open Palm Kettlebell Clean','legs','kettlebell','strength','intermediate'),
('One-Arm_Overhead_Kettlebell_Squats','One-Arm Overhead Kettlebell Squats','legs','kettlebell','strength','expert'),
('One-Arm_Side_Deadlift','One-Arm Side Deadlift','legs','barbell','strength','expert'),
('One-Arm_Side_Laterals','One-Arm Side Laterals','shoulders','dumbbell','strength','beginner'),
('One-Legged_Cable_Kickback','One-Legged Cable Kickback','legs','cable','strength','intermediate'),
('One_Arm_Against_Wall','One Arm Against Wall','back','other','stretching','beginner'),
('One_Arm_Chin-Up','One Arm Chin-Up','back','other','strength','expert'),
('One_Arm_Dumbbell_Bench_Press','One Arm Dumbbell Bench Press','chest','dumbbell','strength','beginner'),
('One_Arm_Dumbbell_Preacher_Curl','One Arm Dumbbell Preacher Curl','arms','dumbbell','strength','beginner'),
('One_Arm_Floor_Press','One Arm Floor Press','arms','barbell','strength','intermediate'),
('One_Arm_Lat_Pulldown','One Arm Lat Pulldown','back','cable','strength','beginner'),
('One_Arm_Pronated_Dumbbell_Triceps_Extension','One Arm Pronated Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('One_Arm_Supinated_Dumbbell_Triceps_Extension','One Arm Supinated Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('One_Half_Locust','One Half Locust','legs','other','stretching','beginner'),
('One_Handed_Hang','One Handed Hang','back','other','stretching','beginner'),
('One_Knee_To_Chest','One Knee To Chest','legs','other','stretching','beginner'),
('One_Leg_Barbell_Squat','One Leg Barbell Squat','legs','barbell','strength','expert'),
('Open_Palm_Kettlebell_Clean','Open Palm Kettlebell Clean','legs','kettlebell','strength','expert'),
('Otis-Up','Otis-Up','core','other','strength','beginner'),
('Overhead_Cable_Curl','Overhead Cable Curl','arms','cable','strength','intermediate'),
('Overhead_Lat','Overhead Lat','back','other','stretching','expert'),
('Overhead_Slam','Overhead Slam','back','other','plyometrics','beginner'),
('Overhead_Squat','Overhead Squat','legs','barbell','olympic weightlifting','expert'),
('Overhead_Stretch','Overhead Stretch','core','other','stretching','beginner'),
('Overhead_Triceps','Overhead Triceps','arms','bodyweight','stretching','expert'),
('Pallof_Press','Pallof Press','core','cable','strength','beginner'),
('Pallof_Press_With_Rotation','Pallof Press With Rotation','core','cable','strength','beginner'),
('Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench','Palms-Down Dumbbell Wrist Curl Over A Bench','arms','dumbbell','strength','beginner'),
('Palms-Down_Wrist_Curl_Over_A_Bench','Palms-Down Wrist Curl Over A Bench','arms','barbell','strength','beginner'),
('Palms-Up_Barbell_Wrist_Curl_Over_A_Bench','Palms-Up Barbell Wrist Curl Over A Bench','arms','barbell','strength','beginner'),
('Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench','Palms-Up Dumbbell Wrist Curl Over A Bench','arms','dumbbell','strength','beginner'),
('Parallel_Bar_Dip','Parallel Bar Dip','arms','other','strength','beginner'),
('Pelvic_Tilt_Into_Bridge','Pelvic Tilt Into Bridge','back','other','stretching','intermediate'),
('Peroneals-SMR','Peroneals-SMR','legs','other','stretching','intermediate'),
('Peroneals_Stretch','Peroneals Stretch','legs','other','stretching','intermediate'),
('Physioball_Hip_Bridge','Physioball Hip Bridge','legs','other','strength','beginner'),
('Pin_Presses','Pin Presses','arms','barbell','powerlifting','intermediate'),
('Piriformis-SMR','Piriformis-SMR','legs','other','stretching','intermediate'),
('Plank','Plank','core','bodyweight','strength','beginner'),
('Plate_Pinch','Plate Pinch','arms','other','strength','intermediate'),
('Plate_Twist','Plate Twist','core','other','strength','intermediate'),
('Platform_Hamstring_Slides','Platform Hamstring Slides','legs','other','strength','beginner'),
('Plie_Dumbbell_Squat','Plie Dumbbell Squat','legs','dumbbell','strength','beginner'),
('Plyo_Kettlebell_Pushups','Plyo Kettlebell Pushups','chest','kettlebell','strength','expert'),
('Plyo_Push-up','Plyo Push-up','chest','bodyweight','plyometrics','beginner'),
('Posterior_Tibialis_Stretch','Posterior Tibialis Stretch','legs','other','stretching','intermediate'),
('Power_Clean','Power Clean','legs','barbell','strength','intermediate'),
('Power_Clean_from_Blocks','Power Clean from Blocks','legs','barbell','olympic weightlifting','intermediate'),
('Power_Jerk','Power Jerk','legs','barbell','olympic weightlifting','expert'),
('Power_Partials','Power Partials','shoulders','dumbbell','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;