INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Power_Snatch','Power Snatch','legs','barbell','olympic weightlifting','expert'),
('Power_Snatch_from_Blocks','Power Snatch from Blocks','legs','barbell','olympic weightlifting','intermediate'),
('Power_Stairs','Power Stairs','legs','other','strongman','intermediate'),
('Preacher_Curl','Preacher Curl','arms','barbell','strength','beginner'),
('Preacher_Hammer_Dumbbell_Curl','Preacher Hammer Dumbbell Curl','arms','dumbbell','strength','beginner'),
('Press_Sit-Up','Press Sit-Up','core','barbell','strength','expert'),
('Prone_Manual_Hamstring','Prone Manual Hamstring','legs','other','strength','beginner'),
('Prowler_Sprint','Prowler Sprint','legs','other','cardio','beginner'),
('Pull_Through','Pull Through','legs','cable','strength','beginner'),
('Pullups','Pullups','back','bodyweight','strength','beginner'),
('Push-Up_Wide','Push-Up Wide','chest','bodyweight','strength','beginner'),
('Push-Ups_-_Close_Triceps_Position','Push-Ups - Close Triceps Position','arms','bodyweight','strength','intermediate'),
('Push-Ups_With_Feet_Elevated','Push-Ups With Feet Elevated','chest','bodyweight','strength','beginner'),
('Push-Ups_With_Feet_On_An_Exercise_Ball','Push-Ups With Feet On An Exercise Ball','chest','other','strength','intermediate'),
('Push_Press','Push Press','shoulders','barbell','olympic weightlifting','expert'),
('Push_Press_-_Behind_the_Neck','Push Press - Behind the Neck','shoulders','barbell','olympic weightlifting','intermediate'),
('Push_Up_to_Side_Plank','Push Up to Side Plank','chest','bodyweight','strength','beginner'),
('Pushups','Pushups','chest','bodyweight','strength','beginner'),
('Pushups_Close_and_Wide_Hand_Positions','Pushups (Close and Wide Hand Positions)','chest','bodyweight','strength','beginner'),
('Pyramid','Pyramid','back','other','stretching','beginner'),
('Quad_Stretch','Quad Stretch','legs','other','stretching','intermediate'),
('Quadriceps-SMR','Quadriceps-SMR','legs','other','stretching','intermediate'),
('Quick_Leap','Quick Leap','legs','other','plyometrics','beginner'),
('Rack_Delivery','Rack Delivery','shoulders','barbell','olympic weightlifting','intermediate'),
('Rack_Pull_with_Bands','Rack Pull with Bands','back','barbell','powerlifting','intermediate'),
('Rack_Pulls','Rack Pulls','back','barbell','powerlifting','intermediate'),
('Rear_Leg_Raises','Rear Leg Raises','legs','bodyweight','stretching','beginner'),
('Recumbent_Bike','Recumbent Bike','legs','machine','cardio','beginner'),
('Return_Push_from_Stance','Return Push from Stance','shoulders','other','plyometrics','beginner'),
('Reverse_Band_Bench_Press','Reverse Band Bench Press','arms','barbell','powerlifting','intermediate'),
('Reverse_Band_Box_Squat','Reverse Band Box Squat','legs','barbell','powerlifting','intermediate'),
('Reverse_Band_Deadlift','Reverse Band Deadlift','back','barbell','powerlifting','expert'),
('Reverse_Band_Power_Squat','Reverse Band Power Squat','legs','barbell','powerlifting','expert'),
('Reverse_Band_Sumo_Deadlift','Reverse Band Sumo Deadlift','legs','barbell','powerlifting','expert'),
('Reverse_Barbell_Curl','Reverse Barbell Curl','arms','barbell','strength','beginner'),
('Reverse_Barbell_Preacher_Curls','Reverse Barbell Preacher Curls','arms','barbell','strength','intermediate'),
('Reverse_Cable_Curl','Reverse Cable Curl','arms','cable','strength','beginner'),
('Reverse_Crunch','Reverse Crunch','core','bodyweight','strength','beginner'),
('Reverse_Flyes','Reverse Flyes','shoulders','dumbbell','strength','beginner'),
('Reverse_Flyes_With_External_Rotation','Reverse Flyes With External Rotation','shoulders','dumbbell','strength','intermediate'),
('Reverse_Grip_Bent-Over_Rows','Reverse Grip Bent-Over Rows','back','barbell','strength','intermediate'),
('Reverse_Grip_Triceps_Pushdown','Reverse Grip Triceps Pushdown','arms','cable','strength','beginner'),
('Reverse_Hyperextension','Reverse Hyperextension','legs','machine','strength','intermediate'),
('Reverse_Machine_Flyes','Reverse Machine Flyes','shoulders','machine','strength','beginner'),
('Reverse_Plate_Curls','Reverse Plate Curls','arms','other','strength','beginner'),
('Reverse_Triceps_Bench_Press','Reverse Triceps Bench Press','arms','barbell','strength','intermediate'),
('Rhomboids-SMR','Rhomboids-SMR','back','other','stretching','intermediate'),
('Rickshaw_Carry','Rickshaw Carry','arms','other','strongman','intermediate'),
('Rickshaw_Deadlift','Rickshaw Deadlift','legs','other','strongman','intermediate'),
('Ring_Dips','Ring Dips','arms','other','strength','intermediate')
ON CONFLICT (external_id) DO NOTHING;