INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Rocket_Jump','Rocket Jump','legs','bodyweight','plyometrics','beginner'),
('Rocking_Standing_Calf_Raise','Rocking Standing Calf Raise','legs','barbell','strength','beginner'),
('Rocky_Pull-Ups_Pulldowns','Rocky Pull-Ups/Pulldowns','back','other','strength','intermediate'),
('Romanian_Deadlift','Romanian Deadlift','legs','barbell','strength','intermediate'),
('Romanian_Deadlift_from_Deficit','Romanian Deadlift from Deficit','legs','barbell','olympic weightlifting','intermediate'),
('Rope_Climb','Rope Climb','back','other','strength','intermediate'),
('Rope_Crunch','Rope Crunch','core','cable','strength','beginner'),
('Rope_Jumping','Rope Jumping','legs','other','cardio','intermediate'),
('Rope_Straight-Arm_Pulldown','Rope Straight-Arm Pulldown','back','cable','strength','beginner'),
('Round_The_World_Shoulder_Stretch','Round The World Shoulder Stretch','shoulders','other','stretching','beginner'),
('Rowing_Stationary','Rowing, Stationary','legs','machine','cardio','intermediate'),
('Runners_Stretch','Runner''s Stretch','legs','other','stretching','beginner'),
('Running_Treadmill','Running, Treadmill','legs','machine','cardio','beginner'),
('Russian_Twist','Russian Twist','core','bodyweight','strength','intermediate'),
('Sandbag_Load','Sandbag Load','legs','other','strongman','beginner'),
('Scapular_Pull-Up','Scapular Pull-Up','back','other','strength','beginner'),
('Scissor_Kick','Scissor Kick','core','bodyweight','stretching','beginner'),
('Scissors_Jump','Scissors Jump','legs','bodyweight','plyometrics','beginner'),
('Seated_Band_Hamstring_Curl','Seated Band Hamstring Curl','legs','other','strength','beginner'),
('Seated_Barbell_Military_Press','Seated Barbell Military Press','shoulders','barbell','strength','intermediate'),
('Seated_Barbell_Twist','Seated Barbell Twist','core','barbell','strength','beginner'),
('Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension','Seated Bent-Over One-Arm Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('Seated_Bent-Over_Rear_Delt_Raise','Seated Bent-Over Rear Delt Raise','shoulders','dumbbell','strength','intermediate'),
('Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension','Seated Bent-Over Two-Arm Dumbbell Triceps Extension','arms','dumbbell','strength','intermediate'),
('Seated_Biceps','Seated Biceps','arms','bodyweight','stretching','expert'),
('Seated_Cable_Rows','Seated Cable Rows','back','cable','strength','beginner'),
('Seated_Cable_Shoulder_Press','Seated Cable Shoulder Press','shoulders','cable','strength','beginner'),
('Seated_Calf_Raise','Seated Calf Raise','legs','machine','strength','beginner'),
('Seated_Calf_Stretch','Seated Calf Stretch','legs','other','stretching','beginner'),
('Seated_Close-Grip_Concentration_Barbell_Curl','Seated Close-Grip Concentration Barbell Curl','arms','barbell','strength','intermediate'),
('Seated_Dumbbell_Curl','Seated Dumbbell Curl','arms','dumbbell','strength','beginner'),
('Seated_Dumbbell_Inner_Biceps_Curl','Seated Dumbbell Inner Biceps Curl','arms','dumbbell','strength','beginner'),
('Seated_Dumbbell_Palms-Down_Wrist_Curl','Seated Dumbbell Palms-Down Wrist Curl','arms','dumbbell','strength','beginner'),
('Seated_Dumbbell_Palms-Up_Wrist_Curl','Seated Dumbbell Palms-Up Wrist Curl','arms','dumbbell','strength','beginner'),
('Seated_Dumbbell_Press','Seated Dumbbell Press','shoulders','dumbbell','strength','beginner'),
('Seated_Flat_Bench_Leg_Pull-In','Seated Flat Bench Leg Pull-In','core','bodyweight','strength','beginner'),
('Seated_Floor_Hamstring_Stretch','Seated Floor Hamstring Stretch','legs','other','stretching','beginner'),
('Seated_Front_Deltoid','Seated Front Deltoid','shoulders','bodyweight','stretching','expert'),
('Seated_Glute','Seated Glute','legs','bodyweight','stretching','expert'),
('Seated_Good_Mornings','Seated Good Mornings','back','barbell','powerlifting','intermediate'),
('Seated_Hamstring','Seated Hamstring','legs','other','stretching','expert'),
('Seated_Hamstring_and_Calf_Stretch','Seated Hamstring and Calf Stretch','legs','other','stretching','intermediate'),
('Seated_Head_Harness_Neck_Resistance','Seated Head Harness Neck Resistance','other','other','strength','intermediate'),
('Seated_Leg_Curl','Seated Leg Curl','legs','machine','strength','beginner'),
('Seated_Leg_Tucks','Seated Leg Tucks','core','bodyweight','strength','beginner'),
('Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl','Seated One-Arm Dumbbell Palms-Down Wrist Curl','arms','dumbbell','strength','intermediate'),
('Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl','Seated One-Arm Dumbbell Palms-Up Wrist Curl','arms','dumbbell','strength','beginner'),
('Seated_One-arm_Cable_Pulley_Rows','Seated One-arm Cable Pulley Rows','back','cable','strength','intermediate'),
('Seated_Overhead_Stretch','Seated Overhead Stretch','core','other','stretching','beginner'),
('Seated_Palm-Up_Barbell_Wrist_Curl','Seated Palm-Up Barbell Wrist Curl','arms','barbell','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;