INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Seated_Palms-Down_Barbell_Wrist_Curl','Seated Palms-Down Barbell Wrist Curl','arms','barbell','strength','beginner'),
('Seated_Side_Lateral_Raise','Seated Side Lateral Raise','shoulders','dumbbell','strength','beginner'),
('Seated_Triceps_Press','Seated Triceps Press','arms','dumbbell','strength','beginner'),
('Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl','Seated Two-Arm Palms-Up Low-Pulley Wrist Curl','arms','cable','strength','beginner'),
('See-Saw_Press_Alternating_Side_Press','See-Saw Press (Alternating Side Press)','shoulders','dumbbell','strength','intermediate'),
('Shotgun_Row','Shotgun Row','back','cable','strength','beginner'),
('Shoulder_Circles','Shoulder Circles','shoulders','other','stretching','beginner'),
('Shoulder_Press_-_With_Bands','Shoulder Press - With Bands','shoulders','bands','strength','beginner'),
('Shoulder_Raise','Shoulder Raise','shoulders','other','stretching','beginner'),
('Shoulder_Stretch','Shoulder Stretch','shoulders','other','stretching','beginner'),
('Side-Lying_Floor_Stretch','Side-Lying Floor Stretch','back','other','stretching','beginner'),
('Side_Bridge','Side Bridge','core','bodyweight','strength','beginner'),
('Side_Hop-Sprint','Side Hop-Sprint','legs','other','plyometrics','beginner'),
('Side_Jackknife','Side Jackknife','core','bodyweight','strength','beginner'),
('Side_Lateral_Raise','Side Lateral Raise','shoulders','dumbbell','strength','beginner'),
('Side_Laterals_to_Front_Raise','Side Laterals to Front Raise','shoulders','dumbbell','strength','beginner'),
('Side_Leg_Raises','Side Leg Raises','legs','bodyweight','stretching','beginner'),
('Side_Lying_Groin_Stretch','Side Lying Groin Stretch','legs','other','stretching','beginner'),
('Side_Neck_Stretch','Side Neck Stretch','other','other','stretching','beginner'),
('Side_Standing_Long_Jump','Side Standing Long Jump','legs','other','plyometrics','beginner'),
('Side_To_Side_Chins','Side To Side Chins','back','other','strength','intermediate'),
('Side_Wrist_Pull','Side Wrist Pull','shoulders','other','stretching','beginner'),
('Side_to_Side_Box_Shuffle','Side to Side Box Shuffle','legs','other','plyometrics','beginner'),
('Single-Arm_Cable_Crossover','Single-Arm Cable Crossover','chest','cable','strength','beginner'),
('Single-Arm_Linear_Jammer','Single-Arm Linear Jammer','shoulders','barbell','strength','intermediate'),
('Single-Arm_Push-Up','Single-Arm Push-Up','chest','bodyweight','strength','intermediate'),
('Single-Cone_Sprint_Drill','Single-Cone Sprint Drill','legs','other','plyometrics','beginner'),
('Single-Leg_High_Box_Squat','Single-Leg High Box Squat','legs','other','strength','beginner'),
('Single-Leg_Hop_Progression','Single-Leg Hop Progression','legs','other','plyometrics','beginner'),
('Single-Leg_Lateral_Hop','Single-Leg Lateral Hop','legs','other','plyometrics','beginner'),
('Single-Leg_Leg_Extension','Single-Leg Leg Extension','legs','machine','strength','beginner'),
('Single-Leg_Stride_Jump','Single-Leg Stride Jump','legs','other','plyometrics','beginner'),
('Single_Dumbbell_Raise','Single Dumbbell Raise','shoulders','dumbbell','strength','beginner'),
('Single_Leg_Butt_Kick','Single Leg Butt Kick','legs','bodyweight','plyometrics','beginner'),
('Single_Leg_Glute_Bridge','Single Leg Glute Bridge','legs','bodyweight','strength','beginner'),
('Single_Leg_Push-off','Single Leg Push-off','legs','other','plyometrics','beginner'),
('Sit-Up','Sit-Up','core','bodyweight','strength','beginner'),
('Sit_Squats','Sit Squats','legs','other','stretching','beginner'),
('Skating','Skating','legs','other','cardio','intermediate'),
('Sled_Drag_-_Harness','Sled Drag - Harness','legs','other','strongman','beginner'),
('Sled_Overhead_Backward_Walk','Sled Overhead Backward Walk','shoulders','other','strength','beginner'),
('Sled_Overhead_Triceps_Extension','Sled Overhead Triceps Extension','arms','other','strength','beginner'),
('Sled_Push','Sled Push','legs','other','strongman','beginner'),
('Sled_Reverse_Flye','Sled Reverse Flye','shoulders','other','strength','beginner'),
('Sled_Row','Sled Row','back','other','strength','beginner'),
('Sledgehammer_Swings','Sledgehammer Swings','core','other','plyometrics','beginner'),
('Smith_Incline_Shoulder_Raise','Smith Incline Shoulder Raise','shoulders','barbell','strength','beginner'),
('Smith_Machine_Behind_the_Back_Shrug','Smith Machine Behind the Back Shrug','back','machine','strength','beginner'),
('Smith_Machine_Bench_Press','Smith Machine Bench Press','chest','machine','strength','beginner'),
('Smith_Machine_Bent_Over_Row','Smith Machine Bent Over Row','back','machine','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;