INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Smith_Machine_Calf_Raise','Smith Machine Calf Raise','legs','machine','strength','beginner'),
('Smith_Machine_Close-Grip_Bench_Press','Smith Machine Close-Grip Bench Press','arms','machine','strength','beginner'),
('Smith_Machine_Decline_Press','Smith Machine Decline Press','chest','machine','strength','beginner'),
('Smith_Machine_Hang_Power_Clean','Smith Machine Hang Power Clean','legs','machine','strength','intermediate'),
('Smith_Machine_Hip_Raise','Smith Machine Hip Raise','core','machine','strength','beginner'),
('Smith_Machine_Incline_Bench_Press','Smith Machine Incline Bench Press','chest','machine','strength','beginner'),
('Smith_Machine_Leg_Press','Smith Machine Leg Press','legs','machine','strength','intermediate'),
('Smith_Machine_One-Arm_Upright_Row','Smith Machine One-Arm Upright Row','shoulders','machine','strength','beginner'),
('Smith_Machine_Overhead_Shoulder_Press','Smith Machine Overhead Shoulder Press','shoulders','machine','strength','beginner'),
('Smith_Machine_Pistol_Squat','Smith Machine Pistol Squat','legs','machine','strength','intermediate'),
('Smith_Machine_Reverse_Calf_Raises','Smith Machine Reverse Calf Raises','legs','machine','strength','beginner'),
('Smith_Machine_Squat','Smith Machine Squat','legs','machine','strength','beginner'),
('Smith_Machine_Stiff-Legged_Deadlift','Smith Machine Stiff-Legged Deadlift','legs','machine','strength','beginner'),
('Smith_Machine_Upright_Row','Smith Machine Upright Row','back','machine','strength','beginner'),
('Smith_Single-Leg_Split_Squat','Smith Single-Leg Split Squat','legs','machine','strength','beginner'),
('Snatch','Snatch','legs','barbell','olympic weightlifting','intermediate'),
('Snatch_Balance','Snatch Balance','legs','barbell','olympic weightlifting','intermediate'),
('Snatch_Deadlift','Snatch Deadlift','legs','barbell','olympic weightlifting','intermediate'),
('Snatch_Pull','Snatch Pull','legs','barbell','strength','intermediate'),
('Snatch_Shrug','Snatch Shrug','back','barbell','olympic weightlifting','intermediate'),
('Snatch_from_Blocks','Snatch from Blocks','legs','barbell','olympic weightlifting','expert'),
('Speed_Band_Overhead_Triceps','Speed Band Overhead Triceps','arms','bands','strength','beginner'),
('Speed_Box_Squat','Speed Box Squat','legs','barbell','powerlifting','intermediate'),
('Speed_Squats','Speed Squats','legs','barbell','strength','expert'),
('Spell_Caster','Spell Caster','core','dumbbell','strength','beginner'),
('Spider_Crawl','Spider Crawl','core','bodyweight','strength','beginner'),
('Spider_Curl','Spider Curl','arms','barbell','strength','beginner'),
('Spinal_Stretch','Spinal Stretch','back','other','stretching','beginner'),
('Split_Clean','Split Clean','legs','barbell','olympic weightlifting','intermediate'),
('Split_Jerk','Split Jerk','legs','barbell','olympic weightlifting','intermediate'),
('Split_Jump','Split Jump','legs','bodyweight','plyometrics','beginner'),
('Split_Snatch','Split Snatch','legs','barbell','olympic weightlifting','expert'),
('Split_Squat_with_Dumbbells','Split Squat with Dumbbells','legs','dumbbell','strength','beginner'),
('Split_Squats','Split Squats','legs','other','stretching','intermediate'),
('Squat_Jerk','Squat Jerk','legs','barbell','strength','expert'),
('Squat_with_Bands','Squat with Bands','legs','barbell','powerlifting','intermediate'),
('Squat_with_Chains','Squat with Chains','legs','barbell','powerlifting','intermediate'),
('Squat_with_Plate_Movers','Squat with Plate Movers','legs','barbell','strength','intermediate'),
('Squats_-_With_Bands','Squats - With Bands','legs','bands','strength','beginner'),
('Stairmaster','Stairmaster','legs','machine','cardio','intermediate'),
('Standing_Alternating_Dumbbell_Press','Standing Alternating Dumbbell Press','shoulders','dumbbell','strength','beginner'),
('Standing_Barbell_Calf_Raise','Standing Barbell Calf Raise','legs','barbell','strength','beginner'),
('Standing_Barbell_Press_Behind_Neck','Standing Barbell Press Behind Neck','shoulders','barbell','strength','intermediate'),
('Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension','Standing Bent-Over One-Arm Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension','Standing Bent-Over Two-Arm Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('Standing_Biceps_Cable_Curl','Standing Biceps Cable Curl','arms','cable','strength','beginner'),
('Standing_Biceps_Stretch','Standing Biceps Stretch','arms','other','stretching','beginner'),
('Standing_Bradford_Press','Standing Bradford Press','shoulders','barbell','strength','beginner'),
('Standing_Cable_Chest_Press','Standing Cable Chest Press','chest','cable','strength','beginner'),
('Standing_Cable_Lift','Standing Cable Lift','core','cable','strength','beginner')
ON CONFLICT (external_id) DO NOTHING;