INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Standing_Cable_Wood_Chop','Standing Cable Wood Chop','core','cable','strength','beginner'),
('Standing_Calf_Raises','Standing Calf Raises','legs','machine','strength','beginner'),
('Standing_Concentration_Curl','Standing Concentration Curl','arms','dumbbell','strength','beginner'),
('Standing_Dumbbell_Calf_Raise','Standing Dumbbell Calf Raise','legs','dumbbell','strength','intermediate'),
('Standing_Dumbbell_Press','Standing Dumbbell Press','shoulders','dumbbell','strength','beginner'),
('Standing_Dumbbell_Reverse_Curl','Standing Dumbbell Reverse Curl','arms','dumbbell','strength','intermediate'),
('Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head','Standing Dumbbell Straight-Arm Front Delt Raise Above Head','shoulders','dumbbell','strength','intermediate'),
('Standing_Dumbbell_Triceps_Extension','Standing Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('Standing_Dumbbell_Upright_Row','Standing Dumbbell Upright Row','back','dumbbell','strength','beginner'),
('Standing_Elevated_Quad_Stretch','Standing Elevated Quad Stretch','legs','other','stretching','beginner'),
('Standing_Front_Barbell_Raise_Over_Head','Standing Front Barbell Raise Over Head','shoulders','barbell','strength','intermediate'),
('Standing_Gastrocnemius_Calf_Stretch','Standing Gastrocnemius Calf Stretch','legs','other','stretching','beginner'),
('Standing_Hamstring_and_Calf_Stretch','Standing Hamstring and Calf Stretch','legs','other','stretching','beginner'),
('Standing_Hip_Circles','Standing Hip Circles','legs','bodyweight','stretching','beginner'),
('Standing_Hip_Flexors','Standing Hip Flexors','legs','other','stretching','beginner'),
('Standing_Inner-Biceps_Curl','Standing Inner-Biceps Curl','arms','dumbbell','strength','intermediate'),
('Standing_Lateral_Stretch','Standing Lateral Stretch','core','other','stretching','beginner'),
('Standing_Leg_Curl','Standing Leg Curl','legs','machine','strength','beginner'),
('Standing_Long_Jump','Standing Long Jump','legs','bodyweight','plyometrics','beginner'),
('Standing_Low-Pulley_Deltoid_Raise','Standing Low-Pulley Deltoid Raise','shoulders','cable','strength','beginner'),
('Standing_Low-Pulley_One-Arm_Triceps_Extension','Standing Low-Pulley One-Arm Triceps Extension','arms','cable','strength','intermediate'),
('Standing_Military_Press','Standing Military Press','shoulders','barbell','strength','beginner'),
('Standing_Olympic_Plate_Hand_Squeeze','Standing Olympic Plate Hand Squeeze','arms','other','strength','beginner'),
('Standing_One-Arm_Cable_Curl','Standing One-Arm Cable Curl','arms','cable','strength','intermediate'),
('Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench','Standing One-Arm Dumbbell Curl Over Incline Bench','arms','dumbbell','strength','beginner'),
('Standing_One-Arm_Dumbbell_Triceps_Extension','Standing One-Arm Dumbbell Triceps Extension','arms','dumbbell','strength','beginner'),
('Standing_Overhead_Barbell_Triceps_Extension','Standing Overhead Barbell Triceps Extension','arms','barbell','strength','beginner'),
('Standing_Palm-In_One-Arm_Dumbbell_Press','Standing Palm-In One-Arm Dumbbell Press','shoulders','dumbbell','strength','beginner'),
('Standing_Palms-In_Dumbbell_Press','Standing Palms-In Dumbbell Press','shoulders','dumbbell','strength','intermediate'),
('Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl','Standing Palms-Up Barbell Behind The Back Wrist Curl','arms','barbell','strength','beginner'),
('Standing_Pelvic_Tilt','Standing Pelvic Tilt','back','other','stretching','beginner'),
('Standing_Rope_Crunch','Standing Rope Crunch','core','cable','strength','beginner'),
('Standing_Soleus_And_Achilles_Stretch','Standing Soleus And Achilles Stretch','legs','other','stretching','beginner'),
('Standing_Toe_Touches','Standing Toe Touches','legs','other','stretching','beginner'),
('Standing_Towel_Triceps_Extension','Standing Towel Triceps Extension','arms','bodyweight','strength','beginner'),
('Standing_Two-Arm_Overhead_Throw','Standing Two-Arm Overhead Throw','shoulders','other','plyometrics','beginner'),
('Star_Jump','Star Jump','legs','bodyweight','plyometrics','beginner'),
('Step-up_with_Knee_Raise','Step-up with Knee Raise','legs','bodyweight','strength','beginner'),
('Step_Mill','Step Mill','legs','machine','cardio','intermediate'),
('Stiff-Legged_Barbell_Deadlift','Stiff-Legged Barbell Deadlift','legs','barbell','strength','intermediate'),
('Stiff-Legged_Dumbbell_Deadlift','Stiff-Legged Dumbbell Deadlift','legs','dumbbell','strength','beginner'),
('Stiff_Leg_Barbell_Good_Morning','Stiff Leg Barbell Good Morning','back','barbell','strength','beginner'),
('Stomach_Vacuum','Stomach Vacuum','core','bodyweight','stretching','beginner'),
('Straight-Arm_Dumbbell_Pullover','Straight-Arm Dumbbell Pullover','chest','dumbbell','strength','intermediate'),
('Straight-Arm_Pulldown','Straight-Arm Pulldown','back','cable','strength','beginner'),
('Straight_Bar_Bench_Mid_Rows','Straight Bar Bench Mid Rows','back','barbell','strength','beginner'),
('Straight_Raises_on_Incline_Bench','Straight Raises on Incline Bench','shoulders','barbell','strength','beginner'),
('Stride_Jump_Crossover','Stride Jump Crossover','legs','other','plyometrics','beginner'),
('Sumo_Deadlift','Sumo Deadlift','legs','barbell','powerlifting','intermediate'),
('Sumo_Deadlift_with_Bands','Sumo Deadlift with Bands','legs','barbell','powerlifting','intermediate')
ON CONFLICT (external_id) DO NOTHING;