INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Sumo_Deadlift_with_Chains','Sumo Deadlift with Chains','legs','barbell','powerlifting','intermediate'),
('Superman','Superman','back','bodyweight','stretching','beginner'),
('Supine_Chest_Throw','Supine Chest Throw','arms','other','plyometrics','beginner'),
('Supine_One-Arm_Overhead_Throw','Supine One-Arm Overhead Throw','core','other','plyometrics','beginner'),
('Supine_Two-Arm_Overhead_Throw','Supine Two-Arm Overhead Throw','core','other','plyometrics','beginner'),
('Suspended_Fallout','Suspended Fallout','core','other','strength','intermediate'),
('Suspended_Push-Up','Suspended Push-Up','chest','other','strength','beginner'),
('Suspended_Reverse_Crunch','Suspended Reverse Crunch','core','other','strength','beginner'),
('Suspended_Row','Suspended Row','back','other','strength','beginner'),
('Suspended_Split_Squat','Suspended Split Squat','legs','other','strength','intermediate'),
('Svend_Press','Svend Press','chest','other','strength','beginner'),
('T-Bar_Row_with_Handle','T-Bar Row with Handle','back','barbell','strength','beginner'),
('Tate_Press','Tate Press','arms','dumbbell','strength','intermediate'),
('The_Straddle','The Straddle','legs','other','stretching','beginner'),
('Thigh_Abductor','Thigh Abductor','legs','machine','strength','beginner'),
('Thigh_Adductor','Thigh Adductor','legs','machine','strength','beginner'),
('Tire_Flip','Tire Flip','legs','other','strongman','intermediate'),
('Toe_Touchers','Toe Touchers','core','bodyweight','stretching','beginner'),
('Torso_Rotation','Torso Rotation','core','other','stretching','beginner'),
('Trail_Running_Walking','Trail Running/Walking','legs','other','cardio','beginner'),
('Trap_Bar_Deadlift','Trap Bar Deadlift','legs','other','strength','beginner'),
('Tricep_Dumbbell_Kickback','Tricep Dumbbell Kickback','arms','dumbbell','strength','beginner'),
('Tricep_Side_Stretch','Tricep Side Stretch','arms','other','stretching','beginner'),
('Triceps_Overhead_Extension_with_Rope','Triceps Overhead Extension with Rope','arms','cable','strength','beginner'),
('Triceps_Pushdown','Triceps Pushdown','arms','cable','strength','beginner'),
('Triceps_Pushdown_-_Rope_Attachment','Triceps Pushdown - Rope Attachment','arms','cable','strength','beginner'),
('Triceps_Pushdown_-_V-Bar_Attachment','Triceps Pushdown - V-Bar Attachment','arms','cable','strength','beginner'),
('Triceps_Stretch','Triceps Stretch','arms','other','stretching','beginner'),
('Tuck_Crunch','Tuck Crunch','core','bodyweight','strength','beginner'),
('Two-Arm_Dumbbell_Preacher_Curl','Two-Arm Dumbbell Preacher Curl','arms','dumbbell','strength','beginner'),
('Two-Arm_Kettlebell_Clean','Two-Arm Kettlebell Clean','shoulders','kettlebell','strength','intermediate'),
('Two-Arm_Kettlebell_Jerk','Two-Arm Kettlebell Jerk','shoulders','kettlebell','strength','intermediate'),
('Two-Arm_Kettlebell_Military_Press','Two-Arm Kettlebell Military Press','shoulders','kettlebell','strength','intermediate'),
('Two-Arm_Kettlebell_Row','Two-Arm Kettlebell Row','back','kettlebell','strength','intermediate'),
('Underhand_Cable_Pulldowns','Underhand Cable Pulldowns','back','cable','strength','beginner'),
('Upper_Back-Leg_Grab','Upper Back-Leg Grab','legs','other','stretching','beginner'),
('Upper_Back_Stretch','Upper Back Stretch','back','other','stretching','beginner'),
('Upright_Barbell_Row','Upright Barbell Row','shoulders','barbell','strength','beginner'),
('Upright_Cable_Row','Upright Cable Row','back','cable','strength','intermediate'),
('Upright_Row_-_With_Bands','Upright Row - With Bands','back','bands','strength','beginner'),
('Upward_Stretch','Upward Stretch','shoulders','other','stretching','beginner'),
('V-Bar_Pulldown','V-Bar Pulldown','back','cable','strength','intermediate'),
('V-Bar_Pullup','V-Bar Pullup','back','bodyweight','strength','beginner'),
('Vertical_Swing','Vertical Swing','legs','dumbbell','plyometrics','beginner'),
('Walking_Treadmill','Walking, Treadmill','legs','machine','cardio','beginner'),
('Weighted_Ball_Hyperextension','Weighted Ball Hyperextension','back','other','strength','intermediate'),
('Weighted_Ball_Side_Bend','Weighted Ball Side Bend','core','other','strength','intermediate'),
('Weighted_Bench_Dip','Weighted Bench Dip','arms','other','strength','intermediate'),
('Weighted_Crunches','Weighted Crunches','core','other','strength','beginner'),
('Weighted_Jump_Squat','Weighted Jump Squat','legs','barbell','strength','intermediate')
ON CONFLICT (external_id) DO NOTHING;