INSERT INTO exercises (external_id, name, muscle_group, equipment, category, level) VALUES
('Weighted_Pull_Ups','Weighted Pull Ups','back','other','strength','intermediate'),
('Weighted_Sissy_Squat','Weighted Sissy Squat','legs','barbell','strength','expert'),
('Weighted_Sit-Ups_-_With_Bands','Weighted Sit-Ups - With Bands','core','other','strength','intermediate'),
('Weighted_Squat','Weighted Squat','legs','other','strength','intermediate'),
('Wide-Grip_Barbell_Bench_Press','Wide-Grip Barbell Bench Press','chest','barbell','strength','intermediate'),
('Wide-Grip_Decline_Barbell_Bench_Press','Wide-Grip Decline Barbell Bench Press','chest','barbell','strength','intermediate'),
('Wide-Grip_Decline_Barbell_Pullover','Wide-Grip Decline Barbell Pullover','chest','barbell','strength','intermediate'),
('Wide-Grip_Lat_Pulldown','Wide-Grip Lat Pulldown','back','cable','strength','beginner'),
('Wide-Grip_Pulldown_Behind_The_Neck','Wide-Grip Pulldown Behind The Neck','back','cable','strength','intermediate'),
('Wide-Grip_Rear_Pull-Up','Wide-Grip Rear Pull-Up','back','bodyweight','strength','intermediate'),
('Wide-Grip_Standing_Barbell_Curl','Wide-Grip Standing Barbell Curl','arms','barbell','strength','beginner'),
('Wide_Stance_Barbell_Squat','Wide Stance Barbell Squat','legs','barbell','strength','intermediate'),
('Wide_Stance_Stiff_Legs','Wide Stance Stiff Legs','legs','barbell','olympic weightlifting','intermediate'),
('Wind_Sprints','Wind Sprints','core','bodyweight','strength','beginner'),
('Windmills','Windmills','legs','other','stretching','intermediate'),
('Worlds_Greatest_Stretch','World''s Greatest Stretch','legs','other','stretching','intermediate'),
('Wrist_Circles','Wrist Circles','arms','bodyweight','stretching','beginner'),
('Wrist_Roller','Wrist Roller','arms','other','strength','beginner'),
('Wrist_Rotations_with_Straight_Bar','Wrist Rotations with Straight Bar','arms','barbell','strength','beginner'),
('Yoke_Walk','Yoke Walk','legs','other','strongman','intermediate'),
('Zercher_Squats','Zercher Squats','legs','barbell','strength','expert'),
('Zottman_Curl','Zottman Curl','arms','dumbbell','strength','intermediate'),
('Zottman_Preacher_Curl','Zottman Preacher Curl','arms','dumbbell','strength','intermediate')
ON CONFLICT (external_id) DO NOTHING;