// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvdgvzfsldvmnmxiysyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZGd2emZzbGR2bW5teGl5c3lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTU2MTYsImV4cCI6MjA3MjQzMTYxNn0.70Or1ZFF-XVzVmLB_jRTOLL-qgUEl837zQAyXC2v8wQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});